### PR TITLE
Quantum Espresso 7.2 Build Scripts

### PR DESCRIPTION
**Pull request by etpalmer63**
Based off advice in help tickets.

### CODE REVIEW

**Comment by etpalmer63** [comment]
Leaving as draft pending rebase.

**Comment by jscook2345** [comment]
Feel free to rebase and re-push

**Comment by etpalmer63** [comment]
Not sure why I'm getting the erroneous message about the line being removed from the abinit script. However, it looks OK nonetheless.

**Comment by etpalmer63** [comment]
Ah.. all better now.

**Pull request merged**
